### ISSUE TITLE
Pod install command fails on arch -x86_64

### ISSUE THREAD

**Issue by wilsonowilson** [nativeshell/nativeshell#43] opened 2021-07-15 10:17 UTC
On apple silicon macs, the pod install build command fails. This should be fixed by using `arch -x86_64 pod install` instead of `pod install` but nativeshell doesn't provide a way to change that command.

Related: https://github.com/CocoaPods/CocoaPods/issues/10723
```
error: failed to run custom build command for `app_template v0.1.0 (/Users/wilson/Developer/Projects/example)`

Caused by:
  process didn't exit successfully: `/Users/wilson/Developer/Projects/example/target/debug/build/app_template-21e5268b40846ea2/build-script-build` (exit status: 101)
  --- stdout

  ** Build failed with error **

  External Tool Failed!
  Status: ExitStatus(ExitStatus(256))
  Command: "\"pod\" \"install\""
  Stderr:
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'ffi' (>= 1.15.0) among 80 total gem(s) (Gem::MissingSpecError)
  Checked in 'GEM_PATH=/Users/wilson/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0', execute `gem env` for more information
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
        from /usr/local/bin/pod:23:in `<main>'

  Stdout:


  --- stderr
  thread 'main' panicked at 'explicit panic', build.rs:26:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```

**Comment by knopp** [comment] 2021-07-15 16:08
I can't seem to be able to reproduce this with examples (cocoa pods version 1.10.1). Which Flutter plugins are you using?

**Comment by wilsonowilson** [comment] 2021-07-15 16:23
`url_launcher` on an M1 Mac.

**Comment by knopp** [comment] 2021-07-15 16:45
Have you tried `sudo gem install ffi` ? From the message it seems that cocoa pods doesn't complain about architecture but about the gem missing completely.

Also when i reinstalled the ffi gem it installed the arm64 version, so I'm a bit hesitant on forcing x86_64 for `pod install`.

**Comment by knopp** [comment] 2021-07-31 16:08
I'm closing this as "cannot reproduce". If you have any additional information that might help me reproduce this feel free to reopen.

**Closed by knopp** 2021-07-31 16:08 UTC
Labels: bug, cannot reproduce
